name: graph_viz_env
channels:
  - conda-forge
  - defaults
  - stellargraph
dependencies:
  - autopep8>=1.5.4
  - black>=20.8b1
  - flake8>=3.8.4
  - ipycytoscape>=1.0.4
  - jedi>=0.18.0
  - jupyter>=1.0.0
  - pytest>=6.2.1
  - pytest-cov>=2.10.1
  - python>=3.7.8
  - rope>=0.18.0
  - seaborn>=0.11.1
  - scipy>=1.6.0
  - scikit-learn>=0.24.0
  - stellargraph>=1.2.1
  - netaddr>=0.7.19
